# Generated by Django 4.1.5 on 2023-03-19 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Renkler')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Renk')),
            ],
        ),
        migrations.CreateModel(
            name='Gander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Cinsiyet')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('text', models.TextField(max_length=1000, verbose_name='Açıklama')),
                ('detail', models.TextField(max_length=800, verbose_name='Özellikler')),
                ('stars', models.FloatField(default=0, verbose_name='Puan')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
                ('colors', models.ManyToManyField(to='appMy.color', verbose_name='Renkler')),
                ('ganders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.gander', verbose_name='Cinsiyet')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Beden')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug Beden')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product', verbose_name='Resim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.size', verbose_name='Beden'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
