# Generated by Django 4.1.5 on 2023-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ManyToManyField(null=True, to='appMy.productimg', verbose_name='Fotoraflar'),
        ),
    ]
