# Generated by Django 4.1.5 on 2023-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_productimg_product_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ManyToManyField(to='appMy.productimg', verbose_name='Fotoraflar'),
        ),
    ]
