# Generated by Django 4.1.5 on 2023-03-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_remove_product_product_img_productimg_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(to='appMy.productimg', verbose_name='Ürün Fotoğrafları')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün')),
            ],
        ),
    ]
