# Generated by Django 4.1.5 on 2023-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_productstok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='appMy.productimg', verbose_name='Resimler'),
        ),
        migrations.DeleteModel(
            name='ProductStok',
        ),
    ]
