# Generated by Django 4.1.5 on 2023-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_remove_productimg_product_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gander',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug Renk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='appMy.productimg', verbose_name='Resimler'),
        ),
    ]
