# Generated by Django 4.1.5 on 2023-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='appMy.productimg', verbose_name='Resimler'),
        ),
    ]
