# Generated by Django 4.1.5 on 2023-03-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Resmin Türü'),
        ),
    ]
