# Generated by Django 4.1.5 on 2023-03-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_alter_productimg_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productimg',
            name='title',
        ),
        migrations.AddField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün'),
        ),
        migrations.CreateModel(
            name='ProductStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(to='appMy.productimg', verbose_name='Ürün Fotoğrafları')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün')),
            ],
        ),
    ]
