# Generated by Django 4.1.5 on 2023-03-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0016_alter_product_ganders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
