# Generated by Django 4.1.5 on 2023-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0017_remove_product_colors_delete_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ürün giriş tarihi'),
        ),
    ]
