# Generated by Django 4.1.5 on 2023-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0018_product_date_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_now',
            field=models.DateTimeField(null=True, verbose_name='Ürün giriş tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='appMy.size', verbose_name='Ürün Beden'),
        ),
    ]
