# Generated by Django 4.1.5 on 2023-03-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0022_product_stok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopbasket',
            old_name='product',
            new_name='productss',
        ),
    ]
