# Generated by Django 4.1.5 on 2023-03-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0024_remove_shopbasket_productss_shopbasket_productss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbasket',
            name='productss',
        ),
        migrations.AddField(
            model_name='shopbasket',
            name='productss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.product', verbose_name='Ürün'),
        ),
    ]
