# Generated by Django 4.1.5 on 2023-03-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0025_remove_shopbasket_productss_shopbasket_productss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstok',
            name='images',
        ),
    ]
