# Generated by Django 4.1.5 on 2023-03-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0026_remove_productstok_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstok',
            name='images',
            field=models.ManyToManyField(to='appMy.productimg', verbose_name='Ürün Fotoğrafları'),
        ),
    ]
