# Generated by Django 4.1.5 on 2023-03-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0028_remove_product_sizes_productstok_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstok',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.size', verbose_name='Ürün Beden'),
        ),
    ]
