# Generated by Django 4.1.5 on 2023-03-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0029_alter_productstok_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbasket',
            name='productss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.productstok', verbose_name='Ürün'),
        ),
    ]
