# Generated by Django 4.1.5 on 2023-03-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0030_alter_shopbasket_productss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstok',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='appMy.size', verbose_name='Ürün beden'),
        ),
    ]
