# Generated by Django 4.1.5 on 2023-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0031_remove_productstok_size_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='appMy.size', verbose_name='Ürün beden'),
        ),
    ]
