# Generated by Django 4.1.5 on 2023-03-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0033_shopbasket_date_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbasket',
            name='date_now',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Sepet Tarihi'),
        ),
    ]
