# Generated by Django 4.1.5 on 2023-03-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0034_alter_shopbasket_date_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstok',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.size', verbose_name='Ürün Beden'),
        ),
    ]
