# Generated by Django 4.1.5 on 2023-03-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0035_productstok_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstok',
            name='size',
        ),
    ]
