# Generated by Django 4.1.5 on 2023-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0038_alter_productstok_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstok',
            name='images',
            field=models.ManyToManyField(to='appMy.productimg', verbose_name='Ürün Fotoğrafları'),
        ),
    ]
