# Generated by Django 4.1.5 on 2023-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0039_alter_productstok_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('title', models.CharField(max_length=50, verbose_name='Mesaj Başlığı')),
                ('text', models.TextField(max_length=1000, verbose_name='Mesaj')),
            ],
        ),
    ]
