# Generated by Django 4.1.5 on 2023-03-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
        ('appMy', '0042_alter_comment_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appUser.userinfo', verbose_name='Profil resmi'),
        ),
    ]
