# Generated by Django 4.1.5 on 2023-03-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0043_comment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
