# Generated by Django 4.1.5 on 2023-03-23 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(default='-', max_length=50, verbose_name='Meslek')),
                ('address', models.CharField(default='-', max_length=50, verbose_name='Adres')),
                ('deneyim', models.IntegerField(default=0, verbose_name='Deneyim')),
                ('image', models.ImageField(default='profilresmi.png', upload_to='', verbose_name='Profil Resmi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('web_site', models.URLField(default='-', verbose_name='Web site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
        ),
    ]
